export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_FILTERED_RESTAURANTS = 'FETCH_FILTERED_RESTAURANTS';
export const FETCH_RESTAURANT_DETAILS = 'FETCH_RESTAURANT_DETAILS';
